version: "3"

services:
  gotify:
    image: gotify/server:2.4.0
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    environment:
      - GOTIFY_DEFAULTUSER_NAME=${GOTIFY_DEFAULTUSER_NAME}
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
    volumes:
      - "./data:/app/data"
    networks:
      - 1panel-network
networks:
    1panel-network:
        external: true