version: '3'
services:
    minio:
      image: minio/minio:RELEASE.2021-06-17T00-10-46Z
      container_name: ${CONTAINER_NAME}
      ports:
        - ${PANEL_APP_PORT}:9000
      restart: always
      command: server /data
      environment:
        MINIO_ACCESS_KEY: ${PANEL_MINIO_ACCESS_KEY}
        MINIO_SECRET_KEY: ${PANEL_MINIO_SECRET_KEY}
      logging:
        options:
          max-size: "1M"
          max-file: "5"
        driver: json-file
      networks:
        - 1panel-network
      volumes:
        - ./data:/data
        - ./config:/root/.minio
      labels:
        createdBy: "Apps"
networks:
  1panel-network:
    external: true    